version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/mrpsycho/docker/jellyfin:/config
      - /home/mrpsycho/mnt/anime/anime/:/media/anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - frontend

  animesonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: animesonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/mrpsycho/docker/sonarr:/config
      - /home/mrpsycho/mnt/anime/anime:/media/anime
      - /home/mrpsycho/mnt/anime/animedownloads:/downloads
    #ports:
    #  - 8989:8989
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true
