version: "3.3"
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/mrpsycho/docker/komga/config
        target: /config
      - type: bind
        source: /home/mrpsycho/docker/komga/data
        target: /data
      - type: bind
        source: /home/mrpsycho/docker/komga/tmp
        target: /tmp
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - Media:/media
    ports:
      - 8080:8080
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    #environment:
    #- <ENV_VAR>=<extra configuration>
    restart: unless-stopped

volumes:
  Media:
    external: true
