version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    #ports:
    #- "8081:8081" (8081 for web inter-face)
    volumes:
      - /home/mrpscyho/mnt/downloads/metube
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true
