version: "3.1"

services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrpsycho
      MONGO_INITDB_ROOT_PASSWORD: mrpsycho42254;

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mrpsycho
      ME_CONFIG_MONGODB_ADMINPASSWORD: mrpsycho42254;
      ME_CONFIG_MONGODB_URL: mongodb://mrpsycho:mrpsycho42254;@mongo:27017/
